server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://samuel:123.abc@localhost:27017/microservices?authSource=admin
  application:
    name : REVIEWS-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: https//localhost:8761/eureka


