server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://samuel:123.abc@localhost:27017/microservices?authSource=admin
  application:
    name : REVIEWS-SERVICE

  config:
    import: configserver:http://localhost:8085
  profiles:
    active: prod


